import type { ScopeSelection, ScopeDimensionOption } from '../../../platform/context';
import { matchesScope } from '../../../platform/context';
import type { DealRecord } from '../types';

let DEAL_RECORDS: DealRecord[] = [
  {
    id: 'atlas-infra-acquisition',
    name: 'Atlas Infrastructure Acquisition',
    owner: 'James Park',
    investmentType: 'Infrastructure',
    taxableIncome: '$4,200,000',
    taxYear: '2026',
    status: 'Active',
    linkedEntityIds: ['atlas-master-fund', 'smith-real-estate-llc'],
    scopeIds: ['atlas-master-fund', 'tax-year-2026'],
    requestCount: 3,
    documentCount: 8,
    openQuestions: 1,
    lastReviewDate: '2026-03-20',
    notes: 'Infrastructure portfolio acquisition through Atlas Master Fund. Ongoing tax structuring review.',
    closingDate: '2026-01-15',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Infrastructure',
    activityLog: [
      { date: '2026-03-20', action: 'Tax structuring memo uploaded', actor: 'James Park' },
      { date: '2026-03-15', action: 'Entity allocation finalized', actor: 'Sarah Chen' },
      { date: '2026-03-01', action: 'Deal created in platform', actor: 'Maria Lopez' },
    ],
    context: {
      fundFamilyLabel: 'Atlas Opportunistic Platform',
      fundLabel: 'Atlas Master Fund',
      parentContextLabel: 'Infrastructure sleeve',
    },
    comments: [],
  },
  {
    id: 'atlas-lux-debt-facility',
    name: 'Atlas Lux Debt Facility',
    owner: 'David Kim',
    investmentType: 'Debt',
    taxableIncome: '$1,850,000',
    taxYear: '2026',
    status: 'Pending Review',
    linkedEntityIds: ['atlas-blocker-lux'],
    scopeIds: ['atlas-blocker-lux', 'tax-year-2026'],
    requestCount: 2,
    documentCount: 5,
    openQuestions: 3,
    lastReviewDate: '2026-03-18',
    notes: 'Lux blocker debt facility with withholding and treaty implications. Under review for 2026 compliance.',
    closingDate: '',
    currency: 'EUR',
    geographicFocus: 'Europe',
    sector: 'Financial Services',
    activityLog: [
      { date: '2026-03-18', action: 'Withholding analysis flagged', actor: 'David Kim' },
      { date: '2026-03-10', action: 'Debt instrument terms uploaded', actor: 'Sarah Chen' },
      { date: '2026-02-20', action: 'Deal created in platform', actor: 'James Park' },
    ],
    context: {
      fundFamilyLabel: 'Atlas Opportunistic Platform',
      fundLabel: 'Atlas Lux Blocker Sleeve',
      parentContextLabel: 'Debt facility',
    },
    comments: [],
  },
  {
    id: 'brep-ix-realty-equity',
    name: 'BREP IX Realty Equity',
    owner: 'Sarah Chen',
    investmentType: 'Real Estate',
    taxableIncome: '$12,500,000',
    taxYear: '2026',
    status: 'Active',
    linkedEntityIds: [],
    scopeIds: ['blackstone-re-ix', 'tax-year-2026'],
    requestCount: 5,
    documentCount: 14,
    openQuestions: 2,
    lastReviewDate: '2026-03-22',
    notes: 'Core real estate equity investment through BREP IX. Multi-state filing exposure.',
    closingDate: '2025-11-30',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Real Estate',
    activityLog: [
      { date: '2026-03-22', action: 'State apportionment review started', actor: 'Sarah Chen' },
      { date: '2026-03-14', action: 'Acquisition closing documents uploaded', actor: 'Maria Lopez' },
      { date: '2026-03-05', action: 'K-1 allocation model drafted', actor: 'James Park' },
      { date: '2026-02-15', action: 'Deal created in platform', actor: 'David Kim' },
    ],
    context: {
      fundFamilyLabel: 'Blackstone Real Estate Partners',
      fundLabel: 'BREP IX',
      parentContextLabel: 'Real estate equity',
    },
    comments: [],
  },
  {
    id: 'smith-re-equity-roll',
    name: 'Smith RE Equity Rollup',
    owner: 'Maria Lopez',
    investmentType: 'Equity',
    taxableIncome: '$780,000',
    taxYear: '2026',
    status: 'Closed',
    linkedEntityIds: ['smith-real-estate-llc', 'drip-ventures-inc'],
    scopeIds: ['atlas-master-fund', 'fed-state-compliance', 'tax-year-2026'],
    requestCount: 1,
    documentCount: 4,
    openQuestions: 0,
    lastReviewDate: '2026-02-28',
    notes: 'Downstream equity rollup through Smith Real Estate holding structure. Closed for 2026.',
    closingDate: '2026-02-28',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Real Estate',
    activityLog: [
      { date: '2026-02-28', action: 'Deal closed — final allocations posted', actor: 'Maria Lopez' },
      { date: '2026-02-15', action: 'Tax memo finalized', actor: 'James Park' },
      { date: '2026-01-20', action: 'Deal created in platform', actor: 'Sarah Chen' },
    ],
    context: {
      fundFamilyLabel: 'Atlas Opportunistic Platform',
      fundLabel: 'Atlas Domestic Holdings',
      parentContextLabel: 'Equity rollup',
    },
    comments: [],
  },
  // --- BIP I & BX Infra deals ---
  {
    id: 'txnm',
    name: 'TXNM',
    owner: 'James Park',
    investmentType: 'Infrastructure',
    taxableIncome: '$3,100,000',
    taxYear: '2026',
    status: 'Active',
    linkedEntityIds: ['txnm-holdings'],
    scopeIds: ['bip-i', 'bx-infra-i', 'tax-year-2026'],
    requestCount: 2,
    documentCount: 6,
    openQuestions: 1,
    lastReviewDate: '2026-03-25',
    notes: 'Transmission and distribution utility investment.',
    closingDate: '2025-12-10',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Infrastructure',
    activityLog: [
      { date: '2026-03-25', action: 'Tax allocation review started', actor: 'James Park' },
      { date: '2026-01-05', action: 'Deal created in platform', actor: 'Sarah Chen' },
    ],
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP I',
      parentContextLabel: 'Utilities',
    },
    comments: [],
  },
  {
    id: 'tallgrass',
    name: 'Tallgrass',
    owner: 'David Kim',
    investmentType: 'Infrastructure',
    taxableIncome: '$2,400,000',
    taxYear: '2026',
    status: 'Active',
    linkedEntityIds: ['tallgrass-opco'],
    scopeIds: ['bip-i', 'tax-year-2026'],
    requestCount: 1,
    documentCount: 4,
    openQuestions: 0,
    lastReviewDate: '2026-03-18',
    notes: 'Midstream energy infrastructure platform.',
    closingDate: '2025-09-20',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Infrastructure',
    activityLog: [
      { date: '2026-03-18', action: 'K-1 draft reviewed', actor: 'David Kim' },
      { date: '2025-10-01', action: 'Deal created in platform', actor: 'Maria Lopez' },
    ],
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP I',
      parentContextLabel: 'Midstream energy',
    },
    comments: [],
  },
  {
    id: 'aspi',
    name: 'ASPI',
    owner: 'Sarah Chen',
    investmentType: 'Infrastructure',
    taxableIncome: '$1,900,000',
    taxYear: '2026',
    status: 'Active',
    linkedEntityIds: [],
    scopeIds: ['bip-i', 'tax-year-2026'],
    requestCount: 2,
    documentCount: 5,
    openQuestions: 1,
    lastReviewDate: '2026-03-20',
    notes: 'Asia-Pacific infrastructure services platform.',
    closingDate: '2025-11-05',
    currency: 'USD',
    geographicFocus: 'Asia-Pacific',
    sector: 'Infrastructure',
    activityLog: [
      { date: '2026-03-20', action: 'Withholding analysis uploaded', actor: 'Sarah Chen' },
      { date: '2025-11-10', action: 'Deal created in platform', actor: 'James Park' },
    ],
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP I',
      parentContextLabel: 'Infrastructure services',
    },
    comments: [],
  },
  {
    id: 'mundys',
    name: 'Mundys',
    owner: 'Maria Lopez',
    investmentType: 'Infrastructure',
    taxableIncome: '$5,600,000',
    taxYear: '2026',
    status: 'Active',
    linkedEntityIds: [],
    scopeIds: ['bip-i', 'tax-year-2026'],
    requestCount: 3,
    documentCount: 7,
    openQuestions: 2,
    lastReviewDate: '2026-03-22',
    notes: 'European transport and mobility infrastructure.',
    closingDate: '2025-08-15',
    currency: 'EUR',
    geographicFocus: 'Europe',
    sector: 'Infrastructure',
    activityLog: [
      { date: '2026-03-22', action: 'Cross-border structuring memo drafted', actor: 'Maria Lopez' },
      { date: '2025-09-01', action: 'Deal created in platform', actor: 'David Kim' },
    ],
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP I',
      parentContextLabel: 'Transport infrastructure',
    },
    comments: [],
  },
  {
    id: 'signature',
    name: 'Signature',
    owner: 'James Park',
    investmentType: 'Infrastructure',
    taxableIncome: '$1,200,000',
    taxYear: '2026',
    status: 'Pending Review',
    linkedEntityIds: [],
    scopeIds: ['bip-i', 'tax-year-2026'],
    requestCount: 1,
    documentCount: 3,
    openQuestions: 1,
    lastReviewDate: '2026-03-10',
    notes: 'Telecommunications infrastructure platform.',
    closingDate: '',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Infrastructure',
    activityLog: [
      { date: '2026-03-10', action: 'Initial tax review started', actor: 'James Park' },
      { date: '2026-02-20', action: 'Deal created in platform', actor: 'Sarah Chen' },
    ],
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP I',
      parentContextLabel: 'Telecom',
    },
    comments: [],
  },
  {
    id: 'cheniere',
    name: 'Cheniere',
    owner: 'David Kim',
    investmentType: 'Infrastructure',
    taxableIncome: '$8,300,000',
    taxYear: '2026',
    status: 'Active',
    linkedEntityIds: [],
    scopeIds: ['bip-i', 'tax-year-2026'],
    requestCount: 4,
    documentCount: 10,
    openQuestions: 0,
    lastReviewDate: '2026-03-28',
    notes: 'LNG export terminal and pipeline infrastructure.',
    closingDate: '2025-06-30',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Infrastructure',
    activityLog: [
      { date: '2026-03-28', action: 'Final K-1 allocation posted', actor: 'David Kim' },
      { date: '2025-07-15', action: 'Deal created in platform', actor: 'Maria Lopez' },
    ],
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP I',
      parentContextLabel: 'Energy infrastructure',
    },
    comments: [],
  },
  {
    id: 'safe-harbor',
    name: 'Safe Harbor',
    owner: 'Sarah Chen',
    investmentType: 'Infrastructure',
    taxableIncome: '$2,700,000',
    taxYear: '2026',
    status: 'Active',
    linkedEntityIds: ['safe-harbor-opco'],
    scopeIds: ['bip-i', 'bx-infra-i', 'tax-year-2026'],
    requestCount: 2,
    documentCount: 5,
    openQuestions: 1,
    lastReviewDate: '2026-03-19',
    notes: 'Marina and waterfront infrastructure portfolio.',
    closingDate: '2025-10-15',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Infrastructure',
    activityLog: [
      { date: '2026-03-19', action: 'Entity structure review completed', actor: 'Sarah Chen' },
      { date: '2025-11-01', action: 'Deal created in platform', actor: 'James Park' },
    ],
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP I / BX Infra I',
      parentContextLabel: 'Marina infrastructure',
    },
    comments: [],
  },
  {
    id: 'powerhouse',
    name: 'Powerhouse',
    owner: 'James Park',
    investmentType: 'Infrastructure',
    taxableIncome: '$4,500,000',
    taxYear: '2026',
    status: 'Active',
    linkedEntityIds: [],
    scopeIds: ['bx-infra-i', 'tax-year-2026'],
    requestCount: 3,
    documentCount: 8,
    openQuestions: 0,
    lastReviewDate: '2026-03-24',
    notes: 'Power generation and renewable energy platform.',
    closingDate: '2025-07-20',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Infrastructure',
    activityLog: [
      { date: '2026-03-24', action: 'Tax compliance package finalized', actor: 'James Park' },
      { date: '2025-08-01', action: 'Deal created in platform', actor: 'David Kim' },
    ],
    context: {
      fundFamilyLabel: 'BX Infrastructure',
      fundLabel: 'BX Infra I',
      parentContextLabel: 'Power generation',
    },
    comments: [],
  },
  // --- BREP IX deals ---
  {
    id: 'amway-hachioji',
    name: 'Amway Hachioji',
    owner: 'Maria Lopez',
    investmentType: 'Real Estate',
    taxableIncome: '$6,800,000',
    taxYear: '2026',
    status: 'Active',
    linkedEntityIds: [],
    scopeIds: ['blackstone-re-ix', 'tax-year-2026'],
    requestCount: 2,
    documentCount: 6,
    openQuestions: 1,
    lastReviewDate: '2026-03-21',
    notes: 'Logistics facility in Hachioji, Japan.',
    closingDate: '2025-10-30',
    currency: 'JPY',
    geographicFocus: 'Asia-Pacific',
    sector: 'Real Estate',
    activityLog: [
      { date: '2026-03-21', action: 'Cross-border withholding review started', actor: 'Maria Lopez' },
      { date: '2025-11-15', action: 'Deal created in platform', actor: 'David Kim' },
    ],
    context: {
      fundFamilyLabel: 'Blackstone Real Estate Partners',
      fundLabel: 'BREP IX',
      parentContextLabel: 'Logistics',
    },
    comments: [],
  },
  {
    id: 'bravo-industrial-portfolio',
    name: 'Bravo Industrial Portfolio',
    owner: 'David Kim',
    investmentType: 'Real Estate',
    taxableIncome: '$9,200,000',
    taxYear: '2026',
    status: 'Active',
    linkedEntityIds: ['bravo-industrial-opco'],
    scopeIds: ['blackstone-re-ix', 'tax-year-2026'],
    requestCount: 3,
    documentCount: 9,
    openQuestions: 2,
    lastReviewDate: '2026-03-26',
    notes: 'Multi-asset industrial portfolio across the US Southeast.',
    closingDate: '2025-08-25',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Real Estate',
    activityLog: [
      { date: '2026-03-26', action: 'State apportionment model updated', actor: 'David Kim' },
      { date: '2025-09-10', action: 'Deal created in platform', actor: 'Sarah Chen' },
    ],
    context: {
      fundFamilyLabel: 'Blackstone Real Estate Partners',
      fundLabel: 'BREP IX',
      parentContextLabel: 'Industrial',
    },
    comments: [],
  },
  {
    id: 'jupiter-industrial-portfolio',
    name: 'Jupiter Industrial Portfolio',
    owner: 'Sarah Chen',
    investmentType: 'Real Estate',
    taxableIncome: '$7,400,000',
    taxYear: '2026',
    status: 'Pending Review',
    linkedEntityIds: [],
    scopeIds: ['blackstone-re-ix', 'tax-year-2026'],
    requestCount: 2,
    documentCount: 7,
    openQuestions: 1,
    lastReviewDate: '2026-03-17',
    notes: 'Industrial logistics portfolio in the US Midwest.',
    closingDate: '2025-09-15',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Real Estate',
    activityLog: [
      { date: '2026-03-17', action: 'Depreciation schedule review initiated', actor: 'Sarah Chen' },
      { date: '2025-10-01', action: 'Deal created in platform', actor: 'James Park' },
    ],
    context: {
      fundFamilyLabel: 'Blackstone Real Estate Partners',
      fundLabel: 'BREP IX',
      parentContextLabel: 'Industrial logistics',
    },
    comments: [],
  },
  {
    id: '15000-aviation',
    name: '15000 Aviation',
    owner: 'James Park',
    investmentType: 'Real Estate',
    taxableIncome: '$3,600,000',
    taxYear: '2026',
    status: 'Active',
    linkedEntityIds: [],
    scopeIds: ['blackstone-re-ix', 'tax-year-2026'],
    requestCount: 1,
    documentCount: 4,
    openQuestions: 0,
    lastReviewDate: '2026-03-15',
    notes: 'Office/mixed-use asset near aviation corridor.',
    closingDate: '2025-12-20',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Real Estate',
    activityLog: [
      { date: '2026-03-15', action: 'Initial tax structuring memo uploaded', actor: 'James Park' },
      { date: '2026-01-05', action: 'Deal created in platform', actor: 'Maria Lopez' },
    ],
    context: {
      fundFamilyLabel: 'Blackstone Real Estate Partners',
      fundLabel: 'BREP IX',
      parentContextLabel: 'Mixed-use',
    },
    comments: [],
  },
  // --- BREP X deals ---
  {
    id: 'test1',
    name: 'Test1',
    owner: 'Maria Lopez',
    investmentType: 'Real Estate',
    taxableIncome: '$1,000,000',
    taxYear: '2026',
    status: 'Active',
    linkedEntityIds: [],
    scopeIds: ['blackstone-re-x', 'tax-year-2026'],
    requestCount: 1,
    documentCount: 2,
    openQuestions: 0,
    lastReviewDate: '2026-03-12',
    notes: 'Test deal for BREP X pipeline.',
    closingDate: '',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Real Estate',
    activityLog: [
      { date: '2026-03-12', action: 'Deal created in platform', actor: 'Maria Lopez' },
    ],
    context: {
      fundFamilyLabel: 'Blackstone Real Estate Partners',
      fundLabel: 'BREP X',
    },
    comments: [],
  },
  {
    id: 'test2',
    name: 'Test2',
    owner: 'David Kim',
    investmentType: 'Real Estate',
    taxableIncome: '$1,500,000',
    taxYear: '2026',
    status: 'Pending Review',
    linkedEntityIds: [],
    scopeIds: ['blackstone-re-x', 'tax-year-2026'],
    requestCount: 1,
    documentCount: 3,
    openQuestions: 1,
    lastReviewDate: '2026-03-14',
    notes: 'Test deal for BREP X pipeline.',
    closingDate: '',
    currency: 'USD',
    geographicFocus: 'North America',
    sector: 'Real Estate',
    activityLog: [
      { date: '2026-03-14', action: 'Deal created in platform', actor: 'David Kim' },
    ],
    context: {
      fundFamilyLabel: 'Blackstone Real Estate Partners',
      fundLabel: 'BREP X',
    },
    comments: [],
  },
];

// Add each deal's own id to its scopeIds so matchesScope works for deal scoping
DEAL_RECORDS = DEAL_RECORDS.map((d) => ({
  ...d,
  scopeIds: d.scopeIds.includes(d.id) ? d.scopeIds : [...d.scopeIds, d.id],
}));

import type { RecordComment } from '../../../types/comment';

let _version = 0;
type Listener = () => void;
const _listeners = new Set<Listener>();
function _notify() { _listeners.forEach((cb) => cb()); }

export const dealsService = {
  getDealScopeDimensionOptions(): ScopeDimensionOption[] {
    return DEAL_RECORDS.map((d) => ({
      id: d.id,
      label: d.name,
      dimension: 'deal' as const,
      description: '',
    }));
  },

  getAccessibleDeals(): DealRecord[] {
    return DEAL_RECORDS;
  },

  getScopedDeals(selection: ScopeSelection): DealRecord[] {
    return DEAL_RECORDS.filter((deal) => matchesScope(deal.scopeIds, selection));
  },

  getAccessibleDealById(id: string): DealRecord | undefined {
    return DEAL_RECORDS.find((deal) => deal.id === id);
  },

  getVersion(): number {
    return _version;
  },

  subscribe(cb: Listener): () => void {
    _listeners.add(cb);
    return () => _listeners.delete(cb);
  },

  addDeal(deal: DealRecord): void {
    DEAL_RECORDS = [deal, ...DEAL_RECORDS];
    _version++;
    _notify();
  },

  updateDeal(id: string, updates: Partial<Omit<DealRecord, 'id'>>): void {
    DEAL_RECORDS = DEAL_RECORDS.map((d) => (d.id === id ? { ...d, ...updates } : d));
    _version++;
    _notify();
  },

  deleteDeal(id: string): void {
    DEAL_RECORDS = DEAL_RECORDS.filter((d) => d.id !== id);
    _version++;
    _notify();
  },

  addDealComment(id: string, comment: RecordComment): void {
    DEAL_RECORDS = DEAL_RECORDS.map((d) =>
      d.id === id ? { ...d, comments: [...d.comments, comment] } : d
    );
    _version++;
    _notify();
  },
};
