import type { ScopeSelection } from '../../../platform/context';
import { matchesScope } from '../../../platform/context';
import type {
  ProcessTemplate,
  ProcessRun,
  ProcessEvent,
  ProcessSummary,
} from '../types';

// ─── Templates ───────────────────────────────────────────────

const PROCESS_TEMPLATES: ProcessTemplate[] = [
  {
    id: 'PTPL-001',
    name: 'Extension Decision Process',
    description: 'End-to-end workflow for evaluating and filing federal/state tax extensions, including multi-state exposure validation and manager sign-off.',
    processType: 'compliance',
    defaultSteps: [
      {
        id: 'PTPLS-001-1',
        title: 'Gather prior-year filing data',
        description: 'Collect all prior-year federal and state filings, extension elections, and payment records.',
        stepType: 'dataGathering',
        order: 1,
        expectedInputs: ['Prior-year filing schedules', 'Payment confirmations', 'Extension records'],
        expectedOutputs: ['Filing data summary'],
        estimatedMinutes: 60,
      },
      {
        id: 'PTPLS-001-2',
        title: 'Validate multi-state exposure positions',
        description: 'Cross-reference state filing requirements against entity nexus analysis and prior positions.',
        stepType: 'validation',
        order: 2,
        expectedInputs: ['State nexus analysis', 'Filing data summary'],
        expectedOutputs: ['State exposure matrix'],
        estimatedMinutes: 90,
      },
      {
        id: 'PTPLS-001-3',
        title: 'Draft extension decision memo',
        description: 'Prepare the decision memorandum documenting the extension rationale, risk assessment, and recommended action.',
        stepType: 'decision',
        order: 3,
        expectedInputs: ['State exposure matrix', 'Filing data summary'],
        expectedOutputs: ['Extension decision memo'],
        estimatedMinutes: 120,
      },
      {
        id: 'PTPLS-001-4',
        title: 'Tax manager review and sign-off',
        description: 'Tax manager reviews the decision memo and provides approval or requests changes.',
        stepType: 'approval',
        order: 4,
        expectedInputs: ['Extension decision memo'],
        expectedOutputs: ['Signed approval'],
        estimatedMinutes: 30,
      },
      {
        id: 'PTPLS-001-5',
        title: 'File extension and confirm receipt',
        description: 'Submit extension filings with relevant authorities and confirm acceptance.',
        stepType: 'manual',
        order: 5,
        expectedInputs: ['Signed approval', 'Filing forms'],
        expectedOutputs: ['Filing confirmation receipts'],
        estimatedMinutes: 45,
      },
    ],
    expectedInputs: ['Prior-year filings', 'Entity nexus data', 'Payment records'],
    expectedOutputs: ['Filed extensions', 'Decision memo', 'Confirmation receipts'],
    tags: ['extension', 'filing', 'decision', 'multi-state'],
    active: true,
    version: 2,
    createdBy: 'Tax Manager',
    createdDate: '2025-11-01',
    lastModifiedDate: '2026-01-15',
    scopeIds: ['atlas-master-fund', 'tax-year-2026', 'fed-state-compliance'],
  },
  {
    id: 'PTPL-002',
    name: 'Withholding Analysis Process',
    description: 'Analyze ownership structures, perform ECI analysis, determine applicable withholding rates, and document conclusions for tax reporting.',
    processType: 'analysis',
    defaultSteps: [
      {
        id: 'PTPLS-002-1',
        title: 'Verify ownership structure',
        description: 'Confirm current ownership chain, beneficial owners, and entity classification for withholding purposes.',
        stepType: 'dataGathering',
        order: 1,
        expectedInputs: ['Ownership diagram', 'Entity classification docs'],
        expectedOutputs: ['Verified ownership chart'],
        estimatedMinutes: 60,
      },
      {
        id: 'PTPLS-002-2',
        title: 'Perform ECI analysis',
        description: 'Evaluate income streams for effectively connected income treatment under applicable tax treaties.',
        stepType: 'validation',
        order: 2,
        expectedInputs: ['Income allocation schedules', 'Treaty positions'],
        expectedOutputs: ['ECI determination worksheet'],
        estimatedMinutes: 120,
      },
      {
        id: 'PTPLS-002-3',
        title: 'Determine withholding rates',
        description: 'Calculate applicable withholding rates based on ECI analysis, treaty benefits, and entity status.',
        stepType: 'decision',
        order: 3,
        expectedInputs: ['ECI determination worksheet', 'W-8 forms'],
        expectedOutputs: ['Withholding rate schedule'],
        estimatedMinutes: 90,
      },
      {
        id: 'PTPLS-002-4',
        title: 'Document conclusions',
        description: 'Prepare final withholding analysis memorandum with supporting documentation.',
        stepType: 'manual',
        order: 4,
        expectedInputs: ['Withholding rate schedule', 'Supporting calculations'],
        expectedOutputs: ['Withholding analysis memo'],
        estimatedMinutes: 60,
      },
    ],
    expectedInputs: ['Ownership docs', 'Income allocations', 'W-8 forms', 'Treaty positions'],
    expectedOutputs: ['Withholding analysis memo', 'Rate schedule'],
    tags: ['withholding', 'ECI', 'treaty', 'analysis'],
    active: true,
    version: 1,
    createdBy: 'International Tax',
    createdDate: '2026-01-10',
    lastModifiedDate: '2026-01-10',
    scopeIds: ['atlas-master-fund', 'tax-year-2026'],
  },
  {
    id: 'PTPL-003',
    name: 'Notice Response Process',
    description: 'Structured workflow for responding to IRS or state tax authority notices, from identification through final submission.',
    processType: 'compliance',
    defaultSteps: [
      {
        id: 'PTPLS-003-1',
        title: 'Identify notice requirements',
        description: 'Review the notice, identify the responding authority, deadline, and required information.',
        stepType: 'review',
        order: 1,
        expectedInputs: ['Original notice', 'Entity filing history'],
        expectedOutputs: ['Notice requirements checklist'],
        estimatedMinutes: 30,
      },
      {
        id: 'PTPLS-003-2',
        title: 'Gather supporting documents',
        description: 'Collect all documents referenced in the notice and any supporting evidence for the response.',
        stepType: 'dataGathering',
        order: 2,
        expectedInputs: ['Notice requirements checklist'],
        expectedOutputs: ['Document package'],
        estimatedMinutes: 90,
      },
      {
        id: 'PTPLS-003-3',
        title: 'Draft response letter',
        description: 'Prepare the formal response addressing each item in the notice with supporting documentation.',
        stepType: 'manual',
        order: 3,
        expectedInputs: ['Document package', 'Notice requirements checklist'],
        expectedOutputs: ['Draft response letter'],
        estimatedMinutes: 120,
      },
      {
        id: 'PTPLS-003-4',
        title: 'Review and submit',
        description: 'Manager review of the draft response, final edits, and submission to the authority.',
        stepType: 'approval',
        order: 4,
        expectedInputs: ['Draft response letter'],
        expectedOutputs: ['Submitted response', 'Proof of delivery'],
        estimatedMinutes: 45,
      },
    ],
    expectedInputs: ['Tax authority notice', 'Filing history', 'Supporting docs'],
    expectedOutputs: ['Submitted response letter', 'Proof of delivery'],
    tags: ['notice', 'response', 'IRS', 'state'],
    active: true,
    version: 1,
    createdBy: 'Tax Operations',
    createdDate: '2026-02-01',
    lastModifiedDate: '2026-02-01',
    scopeIds: ['atlas-master-fund', 'tax-year-2026', 'fed-state-compliance'],
  },
];

// ─── Process Runs ────────────────────────────────────────────

const PROCESS_RUNS: ProcessRun[] = [
  {
    id: 'PRUN-001',
    templateId: 'PTPL-001',
    templateName: 'Extension Decision Process',
    linkedRecord: {
      parentType: 'request',
      parentId: 'REQ-1042',
      parentLabel: 'Extension elections for Atlas Master Fund',
    },
    name: 'Extension Decision — Atlas Master Fund 2026',
    description: 'Evaluate and file 2026 federal and state extensions for Atlas Master Fund, including multi-state exposure review.',
    processType: 'compliance',
    status: 'inProgress',
    owner: 'Tax Manager',
    dueDate: '2026-03-15',
    startedDate: '2026-02-20',
    completedDate: null,
    createdDate: '2026-02-20',
    lastUpdatedDate: '2026-03-10',
    scopeIds: ['atlas-master-fund', 'tax-year-2026', 'fed-state-compliance'],
    steps: [
      {
        id: 'PRS-001-1',
        templateStepId: 'PTPLS-001-1',
        title: 'Gather prior-year filing data',
        description: 'Collect all prior-year federal and state filings, extension elections, and payment records.',
        stepType: 'dataGathering',
        order: 1,
        status: 'completed',
        owner: 'Tax Operations',
        startedDate: '2026-02-20',
        completedDate: '2026-02-22',
        evidence: [
          {
            id: 'EV-001-1',
            source: '2025 Federal filing schedules',
            evidenceType: 'document',
            description: 'Complete set of 2025 federal return schedules including Form 1065 and all K-1s.',
            documentRef: 'DOC-2041',
            addedBy: 'Tax Operations',
            addedDate: '2026-02-21',
          },
          {
            id: 'EV-001-2',
            source: 'State extension payment confirmations',
            evidenceType: 'document',
            description: 'Confirmation receipts for 2025 extension payments across 12 states.',
            documentRef: null,
            addedBy: 'Tax Operations',
            addedDate: '2026-02-22',
          },
        ],
        notes: [
          {
            id: 'N-001-1',
            text: 'All 2025 filings accounted for. No amended returns pending.',
            author: 'Tax Operations',
            timestamp: '2026-02-22T14:30:00Z',
          },
        ],
        decisions: [
          {
            id: 'D-001-1',
            decisionText: 'Prior-year positions confirmed consistent with current year approach.',
            rationale: 'No material changes in entity structure or filing positions between 2025 and 2026. Same states, same entity classifications.',
            decidedBy: 'Tax Manager',
            timestamp: '2026-02-22T16:00:00Z',
          },
        ],
        ruleReferences: [],
        isException: false,
        exceptionReason: null,
        aiAutomationCandidate: true,
        aiAutomationNotes: 'Document gathering from prior-year archives could be automated via document extraction and classification.',
      },
      {
        id: 'PRS-001-2',
        templateStepId: 'PTPLS-001-2',
        title: 'Validate multi-state exposure positions',
        description: 'Cross-reference state filing requirements against entity nexus analysis and prior positions.',
        stepType: 'validation',
        order: 2,
        status: 'completed',
        owner: 'Tax Manager',
        startedDate: '2026-02-23',
        completedDate: '2026-03-01',
        evidence: [
          {
            id: 'EV-001-3',
            source: 'State exposure matrix — 2026',
            evidenceType: 'calculation',
            description: 'Spreadsheet mapping 14 states with nexus triggers, filing requirements, and estimated tax liability.',
            documentRef: null,
            addedBy: 'Tax Manager',
            addedDate: '2026-02-28',
          },
        ],
        notes: [
          {
            id: 'N-001-2',
            text: 'CA and NY filed separately per firm policy. IL added this year due to new office nexus.',
            author: 'Tax Manager',
            timestamp: '2026-03-01T10:15:00Z',
          },
        ],
        decisions: [],
        ruleReferences: [
          {
            ruleId: 'RULE-EXT-001',
            ruleName: 'Multi-state nexus evaluation policy',
            ruleType: 'policy',
            applicationNote: 'Applied nexus threshold test for all states with physical or economic presence.',
          },
        ],
        isException: false,
        exceptionReason: null,
        aiAutomationCandidate: true,
        aiAutomationNotes: 'State exposure matrix generation could be automated by cross-referencing nexus data with filing calendars.',
      },
      {
        id: 'PRS-001-3',
        templateStepId: 'PTPLS-001-3',
        title: 'Draft extension decision memo',
        description: 'Prepare the decision memorandum documenting the extension rationale, risk assessment, and recommended action.',
        stepType: 'decision',
        order: 3,
        status: 'inProgress',
        owner: 'Tax Manager',
        startedDate: '2026-03-03',
        completedDate: null,
        evidence: [
          {
            id: 'EV-001-4',
            source: 'Draft memo — v1',
            evidenceType: 'document',
            description: 'Initial draft of extension decision memo covering federal and 13 of 14 states.',
            documentRef: null,
            addedBy: 'Tax Manager',
            addedDate: '2026-03-08',
          },
        ],
        notes: [
          {
            id: 'N-001-3',
            text: 'Waiting on NJ composite filing data from Tax Operations. Cannot finalize NJ section of memo.',
            author: 'Tax Manager',
            timestamp: '2026-03-08T09:00:00Z',
          },
        ],
        decisions: [
          {
            id: 'D-001-2',
            decisionText: 'Proceed with federal-only extension filing while NJ data is pending.',
            rationale: 'Federal deadline is March 15. NJ composite data expected by March 12. Filing federal now avoids penalty risk while NJ is resolved separately.',
            decidedBy: 'Tax Manager',
            timestamp: '2026-03-08T11:30:00Z',
          },
        ],
        ruleReferences: [
          {
            ruleId: 'RULE-EXT-002',
            ruleName: 'IRC 6081 — Automatic extension filing',
            ruleType: 'external',
            applicationNote: 'Federal automatic 6-month extension applies. State-by-state evaluation required for composite returns.',
          },
        ],
        isException: true,
        exceptionReason: 'NJ composite filing data unavailable — waiting on Tax Operations to provide NJ-CBT-1065 schedules.',
        aiAutomationCandidate: false,
        aiAutomationNotes: '',
      },
      {
        id: 'PRS-001-4',
        templateStepId: 'PTPLS-001-4',
        title: 'Tax manager review and sign-off',
        description: 'Tax manager reviews the decision memo and provides approval or requests changes.',
        stepType: 'approval',
        order: 4,
        status: 'pending',
        owner: 'Tax Manager',
        startedDate: null,
        completedDate: null,
        evidence: [],
        notes: [],
        decisions: [],
        ruleReferences: [],
        isException: false,
        exceptionReason: null,
        aiAutomationCandidate: false,
        aiAutomationNotes: '',
      },
      {
        id: 'PRS-001-5',
        templateStepId: 'PTPLS-001-5',
        title: 'File extension and confirm receipt',
        description: 'Submit extension filings with relevant authorities and confirm acceptance.',
        stepType: 'manual',
        order: 5,
        status: 'pending',
        owner: 'Tax Operations',
        startedDate: null,
        completedDate: null,
        evidence: [],
        notes: [],
        decisions: [],
        ruleReferences: [],
        isException: false,
        exceptionReason: null,
        aiAutomationCandidate: true,
        aiAutomationNotes: 'Filing submission could be automated via e-file API integration with IRS MeF system.',
      },
    ],
  },
  {
    id: 'PRUN-002',
    templateId: 'PTPL-002',
    templateName: 'Withholding Analysis Process',
    linkedRecord: {
      parentType: 'request',
      parentId: 'REQ-1038',
      parentLabel: 'Withholding review for offshore investors',
    },
    name: 'Withholding Analysis — Offshore Investor Group',
    description: 'Analyze withholding requirements for offshore investor allocations in Atlas Master Fund.',
    processType: 'analysis',
    status: 'inProgress',
    owner: 'International Tax',
    dueDate: '2026-04-15',
    startedDate: '2026-03-05',
    completedDate: null,
    createdDate: '2026-03-05',
    lastUpdatedDate: '2026-03-20',
    scopeIds: ['atlas-master-fund', 'tax-year-2026'],
    steps: [
      {
        id: 'PRS-002-1',
        templateStepId: 'PTPLS-002-1',
        title: 'Verify ownership structure',
        description: 'Confirm current ownership chain, beneficial owners, and entity classification for withholding purposes.',
        stepType: 'dataGathering',
        order: 1,
        status: 'completed',
        owner: 'International Tax',
        startedDate: '2026-03-05',
        completedDate: '2026-03-10',
        evidence: [
          {
            id: 'EV-002-1',
            source: 'Fund ownership diagram — Q1 2026',
            evidenceType: 'document',
            description: 'Updated ownership chart showing 23 LPs including 8 offshore entities across 4 jurisdictions.',
            documentRef: null,
            addedBy: 'International Tax',
            addedDate: '2026-03-07',
          },
        ],
        notes: [
          {
            id: 'N-002-1',
            text: 'Ownership verified against Q4 2025 capital account statements. Two new LPs added in Jan 2026.',
            author: 'International Tax',
            timestamp: '2026-03-10T11:00:00Z',
          },
        ],
        decisions: [],
        ruleReferences: [],
        isException: false,
        exceptionReason: null,
        aiAutomationCandidate: true,
        aiAutomationNotes: 'Ownership verification could be automated by cross-referencing capital account records with entity registry.',
      },
      {
        id: 'PRS-002-2',
        templateStepId: 'PTPLS-002-2',
        title: 'Perform ECI analysis',
        description: 'Evaluate income streams for effectively connected income treatment under applicable tax treaties.',
        stepType: 'validation',
        order: 2,
        status: 'inProgress',
        owner: 'International Tax',
        startedDate: '2026-03-11',
        completedDate: null,
        evidence: [],
        notes: [
          {
            id: 'N-002-2',
            text: 'Referencing 2024 ECI position paper as baseline. Reviewing treaty updates for Cayman and Luxembourg entities.',
            author: 'International Tax',
            timestamp: '2026-03-15T14:00:00Z',
          },
        ],
        decisions: [],
        ruleReferences: [
          {
            ruleId: 'RULE-WH-001',
            ruleName: 'ECI determination under IRC 864(c)',
            ruleType: 'external',
            applicationNote: 'Applying trade or business nexus test to each income category for offshore LPs.',
          },
        ],
        isException: false,
        exceptionReason: null,
        aiAutomationCandidate: false,
        aiAutomationNotes: '',
      },
      {
        id: 'PRS-002-3',
        templateStepId: 'PTPLS-002-3',
        title: 'Determine withholding rates',
        description: 'Calculate applicable withholding rates based on ECI analysis, treaty benefits, and entity status.',
        stepType: 'decision',
        order: 3,
        status: 'pending',
        owner: 'International Tax',
        startedDate: null,
        completedDate: null,
        evidence: [],
        notes: [],
        decisions: [],
        ruleReferences: [],
        isException: false,
        exceptionReason: null,
        aiAutomationCandidate: true,
        aiAutomationNotes: 'Rate determination could be partially automated using treaty rate lookup tables and W-8 form data.',
      },
      {
        id: 'PRS-002-4',
        templateStepId: 'PTPLS-002-4',
        title: 'Document conclusions',
        description: 'Prepare final withholding analysis memorandum with supporting documentation.',
        stepType: 'manual',
        order: 4,
        status: 'pending',
        owner: 'International Tax',
        startedDate: null,
        completedDate: null,
        evidence: [],
        notes: [],
        decisions: [],
        ruleReferences: [],
        isException: false,
        exceptionReason: null,
        aiAutomationCandidate: false,
        aiAutomationNotes: '',
      },
    ],
  },
  {
    id: 'PRUN-003',
    templateId: 'PTPL-003',
    templateName: 'Notice Response Process',
    linkedRecord: {
      parentType: 'request',
      parentId: 'REQ-1031',
      parentLabel: 'IRS CP2000 notice for Atlas Blocker',
    },
    name: 'Notice Response — IRS CP2000 Atlas Blocker',
    description: 'Respond to IRS CP2000 notice regarding unreported income discrepancy for Atlas Blocker entity.',
    processType: 'compliance',
    status: 'notStarted',
    owner: 'Tax Operations',
    dueDate: '2026-05-01',
    startedDate: null,
    completedDate: null,
    createdDate: '2026-03-18',
    lastUpdatedDate: '2026-03-18',
    scopeIds: ['atlas-master-fund', 'tax-year-2026', 'fed-state-compliance'],
    steps: [
      {
        id: 'PRS-003-1',
        templateStepId: 'PTPLS-003-1',
        title: 'Identify notice requirements',
        description: 'Review the notice, identify the responding authority, deadline, and required information.',
        stepType: 'review',
        order: 1,
        status: 'pending',
        owner: 'Tax Operations',
        startedDate: null,
        completedDate: null,
        evidence: [],
        notes: [],
        decisions: [],
        ruleReferences: [],
        isException: false,
        exceptionReason: null,
        aiAutomationCandidate: true,
        aiAutomationNotes: 'Notice parsing and requirement extraction could be automated via document AI.',
      },
      {
        id: 'PRS-003-2',
        templateStepId: 'PTPLS-003-2',
        title: 'Gather supporting documents',
        description: 'Collect all documents referenced in the notice and any supporting evidence for the response.',
        stepType: 'dataGathering',
        order: 2,
        status: 'pending',
        owner: 'Tax Operations',
        startedDate: null,
        completedDate: null,
        evidence: [],
        notes: [],
        decisions: [],
        ruleReferences: [],
        isException: false,
        exceptionReason: null,
        aiAutomationCandidate: true,
        aiAutomationNotes: 'Document retrieval from prior filings could be automated based on notice requirements.',
      },
      {
        id: 'PRS-003-3',
        templateStepId: 'PTPLS-003-3',
        title: 'Draft response letter',
        description: 'Prepare the formal response addressing each item in the notice with supporting documentation.',
        stepType: 'manual',
        order: 3,
        status: 'pending',
        owner: 'Tax Operations',
        startedDate: null,
        completedDate: null,
        evidence: [],
        notes: [],
        decisions: [],
        ruleReferences: [],
        isException: false,
        exceptionReason: null,
        aiAutomationCandidate: false,
        aiAutomationNotes: '',
      },
      {
        id: 'PRS-003-4',
        templateStepId: 'PTPLS-003-4',
        title: 'Review and submit',
        description: 'Manager review of the draft response, final edits, and submission to the authority.',
        stepType: 'approval',
        order: 4,
        status: 'pending',
        owner: 'Tax Manager',
        startedDate: null,
        completedDate: null,
        evidence: [],
        notes: [],
        decisions: [],
        ruleReferences: [],
        isException: false,
        exceptionReason: null,
        aiAutomationCandidate: false,
        aiAutomationNotes: '',
      },
    ],
  },
];

// ─── Process Events ──────────────────────────────────────────

const PROCESS_EVENTS: ProcessEvent[] = [
  // PRUN-001 events
  { id: 'EVT-001', runId: 'PRUN-001', eventType: 'created', description: 'Process run created from template "Extension Decision Process"', actor: 'Tax Manager', timestamp: '2026-02-20T09:00:00Z', stepId: null, metadata: { templateId: 'PTPL-001' } },
  { id: 'EVT-002', runId: 'PRUN-001', eventType: 'statusChange', description: 'Run status changed to In Progress', actor: 'Tax Manager', timestamp: '2026-02-20T09:05:00Z', stepId: null, metadata: { from: 'notStarted', to: 'inProgress' } },
  { id: 'EVT-003', runId: 'PRUN-001', eventType: 'stepStarted', description: 'Step 1 "Gather prior-year filing data" started', actor: 'Tax Operations', timestamp: '2026-02-20T10:00:00Z', stepId: 'PRS-001-1', metadata: {} },
  { id: 'EVT-004', runId: 'PRUN-001', eventType: 'evidenceAdded', description: 'Added 2025 Federal filing schedules', actor: 'Tax Operations', timestamp: '2026-02-21T14:00:00Z', stepId: 'PRS-001-1', metadata: { evidenceId: 'EV-001-1' } },
  { id: 'EVT-005', runId: 'PRUN-001', eventType: 'evidenceAdded', description: 'Added state extension payment confirmations', actor: 'Tax Operations', timestamp: '2026-02-22T10:00:00Z', stepId: 'PRS-001-1', metadata: { evidenceId: 'EV-001-2' } },
  { id: 'EVT-006', runId: 'PRUN-001', eventType: 'decisionRecorded', description: 'Decision: Prior-year positions confirmed consistent', actor: 'Tax Manager', timestamp: '2026-02-22T16:00:00Z', stepId: 'PRS-001-1', metadata: { decisionId: 'D-001-1' } },
  { id: 'EVT-007', runId: 'PRUN-001', eventType: 'stepCompleted', description: 'Step 1 "Gather prior-year filing data" completed', actor: 'Tax Operations', timestamp: '2026-02-22T17:00:00Z', stepId: 'PRS-001-1', metadata: {} },
  { id: 'EVT-008', runId: 'PRUN-001', eventType: 'stepStarted', description: 'Step 2 "Validate multi-state exposure" started', actor: 'Tax Manager', timestamp: '2026-02-23T09:00:00Z', stepId: 'PRS-001-2', metadata: {} },
  { id: 'EVT-009', runId: 'PRUN-001', eventType: 'ruleReferenced', description: 'Referenced: Multi-state nexus evaluation policy', actor: 'Tax Manager', timestamp: '2026-02-28T15:00:00Z', stepId: 'PRS-001-2', metadata: { ruleId: 'RULE-EXT-001' } },
  { id: 'EVT-010', runId: 'PRUN-001', eventType: 'stepCompleted', description: 'Step 2 "Validate multi-state exposure" completed', actor: 'Tax Manager', timestamp: '2026-03-01T11:00:00Z', stepId: 'PRS-001-2', metadata: {} },
  { id: 'EVT-011', runId: 'PRUN-001', eventType: 'stepStarted', description: 'Step 3 "Draft extension decision memo" started', actor: 'Tax Manager', timestamp: '2026-03-03T09:00:00Z', stepId: 'PRS-001-3', metadata: {} },
  { id: 'EVT-012', runId: 'PRUN-001', eventType: 'exceptionFlagged', description: 'Exception: NJ composite filing data unavailable', actor: 'Tax Manager', timestamp: '2026-03-08T09:00:00Z', stepId: 'PRS-001-3', metadata: { reason: 'NJ composite filing data unavailable' } },
  { id: 'EVT-013', runId: 'PRUN-001', eventType: 'decisionRecorded', description: 'Decision: Proceed with federal-only extension while NJ is pending', actor: 'Tax Manager', timestamp: '2026-03-08T11:30:00Z', stepId: 'PRS-001-3', metadata: { decisionId: 'D-001-2' } },
  // PRUN-002 events
  { id: 'EVT-014', runId: 'PRUN-002', eventType: 'created', description: 'Process run created from template "Withholding Analysis Process"', actor: 'International Tax', timestamp: '2026-03-05T10:00:00Z', stepId: null, metadata: { templateId: 'PTPL-002' } },
  { id: 'EVT-015', runId: 'PRUN-002', eventType: 'statusChange', description: 'Run status changed to In Progress', actor: 'International Tax', timestamp: '2026-03-05T10:05:00Z', stepId: null, metadata: { from: 'notStarted', to: 'inProgress' } },
  { id: 'EVT-016', runId: 'PRUN-002', eventType: 'stepStarted', description: 'Step 1 "Verify ownership structure" started', actor: 'International Tax', timestamp: '2026-03-05T10:30:00Z', stepId: 'PRS-002-1', metadata: {} },
  { id: 'EVT-017', runId: 'PRUN-002', eventType: 'stepCompleted', description: 'Step 1 "Verify ownership structure" completed', actor: 'International Tax', timestamp: '2026-03-10T16:00:00Z', stepId: 'PRS-002-1', metadata: {} },
  { id: 'EVT-018', runId: 'PRUN-002', eventType: 'stepStarted', description: 'Step 2 "Perform ECI analysis" started', actor: 'International Tax', timestamp: '2026-03-11T09:00:00Z', stepId: 'PRS-002-2', metadata: {} },
  // PRUN-003 events
  { id: 'EVT-019', runId: 'PRUN-003', eventType: 'created', description: 'Process run created from template "Notice Response Process"', actor: 'Tax Operations', timestamp: '2026-03-18T14:00:00Z', stepId: null, metadata: { templateId: 'PTPL-003' } },
];

// ─── Service ─────────────────────────────────────────────────

// Future AI integration point: processService methods could be augmented with
// AI-powered suggestions (next steps, pattern detection, bottleneck identification).

export const processService = {
  // Templates
  getAllTemplates(): ProcessTemplate[] {
    return PROCESS_TEMPLATES;
  },

  getActiveTemplates(): ProcessTemplate[] {
    return PROCESS_TEMPLATES.filter((t) => t.active);
  },

  getTemplateById(id: string): ProcessTemplate | undefined {
    return PROCESS_TEMPLATES.find((t) => t.id === id);
  },

  // Runs
  getAllRuns(): ProcessRun[] {
    return PROCESS_RUNS;
  },

  getRunById(id: string): ProcessRun | undefined {
    return PROCESS_RUNS.find((r) => r.id === id);
  },

  getRunsByParent(parentType: string, parentId: string): ProcessRun[] {
    return PROCESS_RUNS.filter(
      (r) => r.linkedRecord.parentType === parentType && r.linkedRecord.parentId === parentId,
    );
  },

  getScopedRuns(selection: ScopeSelection): ProcessRun[] {
    return PROCESS_RUNS.filter((r) => matchesScope(r.scopeIds, selection));
  },

  // Events
  getEventsByRunId(runId: string): ProcessEvent[] {
    return PROCESS_EVENTS.filter((e) => e.runId === runId).sort(
      (a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime(),
    );
  },

  // Computed
  getProcessSummary(run: ProcessRun): ProcessSummary {
    const completedSteps = run.steps.filter((s) => s.status === 'completed').length;
    const totalSteps = run.steps.length;
    const currentStep = run.steps.find((s) => s.status === 'inProgress' || s.status === 'pending');
    const exceptionCount = run.steps.filter((s) => s.isException).length;

    return {
      runId: run.id,
      runName: run.name,
      templateName: run.templateName,
      status: run.status,
      totalSteps,
      completedSteps,
      percentComplete: totalSteps > 0 ? Math.round((completedSteps / totalSteps) * 100) : 0,
      currentStepTitle: currentStep?.title ?? null,
      exceptionCount,
      owner: run.owner,
      dueDate: run.dueDate,
      lastUpdatedDate: run.lastUpdatedDate,
    };
  },

  getProcessSummariesByParent(parentType: string, parentId: string): ProcessSummary[] {
    return this.getRunsByParent(parentType, parentId).map((r) => this.getProcessSummary(r));
  },
};
