import type { ScopeSelection } from '../../../platform/context';
import { matchesScope } from '../../../platform/context';
import type { EntityRecord } from '../types';
import type { RecordComment } from '../../../types/comment';

let _version = 0;
type Listener = () => void;
const _listeners = new Set<Listener>();
function _notify() { _listeners.forEach((cb) => cb()); }

let ENTITY_RECORDS: EntityRecord[] = [
  // --- Fund Vehicles ---
  {
    id: 'bip-i-lp',
    name: 'BIP I, L.P.',
    legalName: 'BIP I, L.P.',
    category: 'Fund Vehicle',
    jurisdiction: 'Cayman Islands',
    status: 'Active',
    taxClassification: 'Partnership',
    ownerTeam: 'Fund Tax',
    scopeIds: ['bip-i', 'tax-year-2026'],
    associatedFundIds: ['bip-i'],
    associatedDealIds: [],
    structureSummary: 'Primary fund vehicle for Blackstone Infrastructure Partners I.',
    requestCount: 5,
    documentCount: 14,
    openQuestions: 1,
    lastReviewDate: '2026-03-20',
    notes: 'Year-end filing coordination and investor allocations for BIP I.',
    ein: '98-7654321',
    dateFormed: '2019-03-15',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'Maples Corporate Services',
    address: 'PO Box 309, Ugland House, George Town, Grand Cayman',
    checkTheBoxElection: 'N/A — foreign partnership',
    treatyCountry: 'Cayman Islands',
    fatcaStatus: 'Sponsoring entity — IGA Model 1',
    stateFilingJurisdictions: [],
    structureRole: 'Master Fund',
    formationType: 'LP',
    functionalCurrency: 'USD',
    taxReportingStatus: 'None',
    annualRevenue: '$45,000,000',
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP I',
      parentContextLabel: 'Fund vehicle',
    },
    activityLog: [
      { date: '2026-03-20', action: 'Year-end review initiated', actor: 'Sarah Chen' },
      { date: '2026-03-10', action: 'K-1 draft packages uploaded', actor: 'System' },
    ],
    comments: [],
  },
  {
    id: 'bx-infra-i-lp',
    name: 'BX Infra I, L.P.',
    legalName: 'BX Infra I, L.P.',
    category: 'Fund Vehicle',
    jurisdiction: 'Delaware',
    status: 'Active',
    taxClassification: 'Partnership',
    ownerTeam: 'Fund Tax',
    scopeIds: ['bx-infra-i', 'tax-year-2026'],
    associatedFundIds: ['bx-infra-i'],
    associatedDealIds: [],
    structureSummary: 'Primary fund vehicle for BX Infrastructure I.',
    requestCount: 3,
    documentCount: 10,
    openQuestions: 0,
    lastReviewDate: '2026-03-18',
    notes: 'BX Infra I fund entity — domestic LP.',
    ein: '84-3321567',
    dateFormed: '2020-06-01',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'Corporation Trust Company',
    address: '1209 Orange St, Wilmington, DE 19801',
    checkTheBoxElection: 'N/A — domestic partnership',
    treatyCountry: 'N/A',
    fatcaStatus: 'N/A — domestic entity',
    stateFilingJurisdictions: ['Delaware'],
    structureRole: 'Master Fund',
    formationType: 'LP',
    functionalCurrency: 'USD',
    taxReportingStatus: 'None',
    annualRevenue: '$32,000,000',
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BX Infra I',
      parentContextLabel: 'Fund vehicle',
    },
    activityLog: [
      { date: '2026-03-18', action: 'Year-end review completed', actor: 'James Park' },
    ],
    comments: [],
  },
  {
    id: 'brep-ix-lp',
    name: 'BREP IX, L.P.',
    legalName: 'BREP IX, L.P.',
    category: 'Fund Vehicle',
    jurisdiction: 'Delaware',
    status: 'Active',
    taxClassification: 'Partnership',
    ownerTeam: 'Fund Tax',
    scopeIds: ['blackstone-re-ix', 'tax-year-2026'],
    associatedFundIds: ['blackstone-re-ix'],
    associatedDealIds: [],
    structureSummary: 'Primary fund vehicle for Blackstone Real Estate Partners IX.',
    requestCount: 6,
    documentCount: 16,
    openQuestions: 2,
    lastReviewDate: '2026-03-22',
    notes: 'BREP IX fund entity — core real estate fund.',
    ein: '47-8876543',
    dateFormed: '2018-11-20',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'Corporation Trust Company',
    address: '1209 Orange St, Wilmington, DE 19801',
    checkTheBoxElection: 'N/A — domestic partnership',
    treatyCountry: 'N/A',
    fatcaStatus: 'N/A — domestic entity',
    stateFilingJurisdictions: ['Delaware', 'New York'],
    structureRole: 'Master Fund',
    formationType: 'LP',
    functionalCurrency: 'USD',
    taxReportingStatus: 'None',
    annualRevenue: '$85,000,000',
    context: {
      fundFamilyLabel: 'Blackstone Real Estate Partners',
      fundLabel: 'BREP IX',
      parentContextLabel: 'Fund vehicle',
    },
    activityLog: [
      { date: '2026-03-22', action: 'K-1 allocation model finalized', actor: 'Sarah Chen' },
      { date: '2026-03-15', action: 'Year-end review initiated', actor: 'David Kim' },
    ],
    comments: [],
  },
  {
    id: 'brep-x-lp',
    name: 'BREP X, L.P.',
    legalName: 'BREP X, L.P.',
    category: 'Fund Vehicle',
    jurisdiction: 'Delaware',
    status: 'Pending Review',
    taxClassification: 'Partnership',
    ownerTeam: 'Fund Tax',
    scopeIds: ['blackstone-re-x', 'tax-year-2026'],
    associatedFundIds: ['blackstone-re-x'],
    associatedDealIds: [],
    structureSummary: 'Primary fund vehicle for Blackstone Real Estate Partners X.',
    requestCount: 1,
    documentCount: 3,
    openQuestions: 1,
    lastReviewDate: '2026-03-14',
    notes: 'BREP X fund entity — newly formed.',
    ein: '92-1234567',
    dateFormed: '2025-09-01',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'Corporation Trust Company',
    address: '1209 Orange St, Wilmington, DE 19801',
    checkTheBoxElection: 'N/A — domestic partnership',
    treatyCountry: 'N/A',
    fatcaStatus: 'N/A — domestic entity',
    stateFilingJurisdictions: ['Delaware'],
    structureRole: 'Master Fund',
    formationType: 'LP',
    functionalCurrency: 'USD',
    taxReportingStatus: 'None',
    annualRevenue: '$5,000,000',
    context: {
      fundFamilyLabel: 'Blackstone Real Estate Partners',
      fundLabel: 'BREP X',
      parentContextLabel: 'Fund vehicle',
    },
    activityLog: [
      { date: '2026-03-14', action: 'Entity created in platform', actor: 'Maria Lopez' },
    ],
    comments: [],
  },
  // --- Operating Companies ---
  {
    id: 'txnm-holdings',
    name: 'TXNM Holdings LLC',
    legalName: 'TXNM Holdings LLC',
    category: 'Investment Level',
    jurisdiction: 'Delaware',
    status: 'Active',
    taxClassification: 'Partnership',
    ownerTeam: 'Portfolio Reporting',
    scopeIds: ['bip-i', 'bx-infra-i', 'tax-year-2026'],
    associatedFundIds: [],
    associatedDealIds: ['txnm'],
    structureSummary: 'Operating company for TXNM transmission and distribution utility investment.',
    requestCount: 2,
    documentCount: 6,
    openQuestions: 1,
    lastReviewDate: '2026-03-25',
    notes: 'OpCo for TXNM deal — utility sector.',
    ein: '82-9901234',
    dateFormed: '2021-04-10',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'CSC — Lawyers Incorporating Service',
    address: '251 Little Falls Dr, Wilmington, DE 19808',
    checkTheBoxElection: 'N/A — domestic partnership',
    treatyCountry: 'N/A',
    fatcaStatus: 'N/A — domestic entity',
    stateFilingJurisdictions: ['Delaware', 'New Mexico', 'Texas'],
    structureRole: 'Operating Company',
    formationType: 'LLC',
    functionalCurrency: 'USD',
    taxReportingStatus: 'None',
    annualRevenue: '$3,100,000',
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP I / BX Infra I',
      parentContextLabel: 'TXNM deal OpCo',
    },
    activityLog: [
      { date: '2026-03-25', action: 'Tax allocation review started', actor: 'James Park' },
      { date: '2026-01-05', action: 'Entity created in platform', actor: 'Sarah Chen' },
    ],
    comments: [],
  },
  {
    id: 'tallgrass-opco',
    name: 'Tallgrass Energy OpCo LLC',
    legalName: 'Tallgrass Energy OpCo LLC',
    category: 'Investment Level',
    jurisdiction: 'Delaware',
    status: 'Active',
    taxClassification: 'Partnership',
    ownerTeam: 'Portfolio Reporting',
    scopeIds: ['bip-i', 'tax-year-2026'],
    associatedFundIds: [],
    associatedDealIds: ['tallgrass'],
    structureSummary: 'Operating company for Tallgrass midstream energy infrastructure.',
    requestCount: 1,
    documentCount: 4,
    openQuestions: 0,
    lastReviewDate: '2026-03-18',
    notes: 'OpCo for Tallgrass deal — midstream energy.',
    ein: '83-5567890',
    dateFormed: '2020-09-15',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'Corporation Trust Company',
    address: '1209 Orange St, Wilmington, DE 19801',
    checkTheBoxElection: 'N/A — domestic partnership',
    treatyCountry: 'N/A',
    fatcaStatus: 'N/A — domestic entity',
    stateFilingJurisdictions: ['Delaware', 'Kansas', 'Colorado'],
    structureRole: 'Operating Company',
    formationType: 'LLC',
    functionalCurrency: 'USD',
    taxReportingStatus: 'None',
    annualRevenue: '$2,400,000',
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP I',
      parentContextLabel: 'Tallgrass deal OpCo',
    },
    activityLog: [
      { date: '2026-03-18', action: 'K-1 draft reviewed', actor: 'David Kim' },
    ],
    comments: [],
  },
  {
    id: 'bravo-industrial-opco',
    name: 'Bravo Industrial OpCo LLC',
    legalName: 'Bravo Industrial OpCo LLC',
    category: 'Investment Level',
    jurisdiction: 'Delaware',
    status: 'Active',
    taxClassification: 'Partnership',
    ownerTeam: 'Portfolio Reporting',
    scopeIds: ['blackstone-re-ix', 'tax-year-2026'],
    associatedFundIds: [],
    associatedDealIds: ['bravo-industrial-portfolio'],
    structureSummary: 'Operating company for Bravo Industrial Portfolio across the US Southeast.',
    requestCount: 3,
    documentCount: 9,
    openQuestions: 2,
    lastReviewDate: '2026-03-26',
    notes: 'OpCo for Bravo Industrial deal — multi-asset industrial portfolio.',
    ein: '85-6789012',
    dateFormed: '2021-08-20',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'Corporation Trust Company',
    address: '1209 Orange St, Wilmington, DE 19801',
    checkTheBoxElection: 'N/A — domestic partnership',
    treatyCountry: 'N/A',
    fatcaStatus: 'N/A — domestic entity',
    stateFilingJurisdictions: ['Delaware', 'Georgia', 'Florida', 'North Carolina'],
    structureRole: 'Operating Company',
    formationType: 'LLC',
    functionalCurrency: 'USD',
    taxReportingStatus: 'None',
    annualRevenue: '$9,200,000',
    context: {
      fundFamilyLabel: 'Blackstone Real Estate Partners',
      fundLabel: 'BREP IX',
      parentContextLabel: 'Bravo Industrial deal OpCo',
    },
    activityLog: [
      { date: '2026-03-26', action: 'State apportionment model updated', actor: 'David Kim' },
    ],
    comments: [],
  },
  {
    id: 'safe-harbor-opco',
    name: 'Safe Harbor Marinas OpCo LLC',
    legalName: 'Safe Harbor Marinas OpCo LLC',
    category: 'Investment Level',
    jurisdiction: 'Delaware',
    status: 'Active',
    taxClassification: 'Partnership',
    ownerTeam: 'Portfolio Reporting',
    scopeIds: ['bip-i', 'bx-infra-i', 'tax-year-2026'],
    associatedFundIds: [],
    associatedDealIds: ['safe-harbor'],
    structureSummary: 'Operating company for Safe Harbor marina and waterfront infrastructure.',
    requestCount: 2,
    documentCount: 5,
    openQuestions: 1,
    lastReviewDate: '2026-03-19',
    notes: 'OpCo for Safe Harbor deal — marina infrastructure.',
    ein: '84-1234567',
    dateFormed: '2021-10-01',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'CSC — Lawyers Incorporating Service',
    address: '251 Little Falls Dr, Wilmington, DE 19808',
    checkTheBoxElection: 'N/A — domestic partnership',
    treatyCountry: 'N/A',
    fatcaStatus: 'N/A — domestic entity',
    stateFilingJurisdictions: ['Delaware', 'Florida', 'Maryland'],
    structureRole: 'Operating Company',
    formationType: 'LLC',
    functionalCurrency: 'USD',
    taxReportingStatus: 'None',
    annualRevenue: '$2,700,000',
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP I / BX Infra I',
      parentContextLabel: 'Safe Harbor deal OpCo',
    },
    activityLog: [
      { date: '2026-03-19', action: 'Entity structure review completed', actor: 'Sarah Chen' },
    ],
    comments: [],
  },
  // --- Holding Companies ---
  {
    id: 'bip-holdings-llc',
    name: 'BIP Holdings LLC',
    legalName: 'BIP Holdings LLC',
    category: 'Holding Company',
    jurisdiction: 'Delaware',
    status: 'Active',
    taxClassification: 'Partnership',
    ownerTeam: 'Tax Operations',
    scopeIds: ['bip-i', 'bx-infra-i', 'tax-year-2026'],
    associatedFundIds: ['bip-i', 'bx-infra-i'],
    associatedDealIds: [],
    structureSummary: 'Holding company aggregating infrastructure investments across BIP I and BX Infra I.',
    requestCount: 3,
    documentCount: 8,
    openQuestions: 1,
    lastReviewDate: '2026-03-15',
    notes: 'Holding entity for infrastructure fund investments.',
    ein: '47-5559876',
    dateFormed: '2019-07-22',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'Corporation Trust Company',
    address: '1209 Orange St, Wilmington, DE 19801',
    checkTheBoxElection: 'N/A — domestic partnership',
    treatyCountry: 'N/A',
    fatcaStatus: 'N/A — domestic entity',
    stateFilingJurisdictions: ['Delaware', 'New York'],
    structureRole: 'Holding Company',
    formationType: 'LLC',
    functionalCurrency: 'USD',
    taxReportingStatus: 'None',
    annualRevenue: '$12,000,000',
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP I / BX Infra I',
      parentContextLabel: 'Infrastructure holding entity',
    },
    activityLog: [
      { date: '2026-03-15', action: 'State composite return prep started', actor: 'James Park' },
      { date: '2026-03-06', action: 'Delaware franchise tax filed', actor: 'System' },
    ],
    comments: [],
  },
  {
    id: 'brep-holdings-llc',
    name: 'BREP Holdings LLC',
    legalName: 'BREP Holdings LLC',
    category: 'Holding Company',
    jurisdiction: 'Delaware',
    status: 'Active',
    taxClassification: 'Partnership',
    ownerTeam: 'Tax Operations',
    scopeIds: ['blackstone-re-ix', 'tax-year-2026'],
    associatedFundIds: ['blackstone-re-ix'],
    associatedDealIds: [],
    structureSummary: 'Holding company for BREP IX real estate investments.',
    requestCount: 2,
    documentCount: 6,
    openQuestions: 0,
    lastReviewDate: '2026-03-20',
    notes: 'Holding entity for BREP IX downstream investments.',
    ein: '48-9988776',
    dateFormed: '2019-01-10',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'Corporation Trust Company',
    address: '1209 Orange St, Wilmington, DE 19801',
    checkTheBoxElection: 'N/A — domestic partnership',
    treatyCountry: 'N/A',
    fatcaStatus: 'N/A — domestic entity',
    stateFilingJurisdictions: ['Delaware'],
    structureRole: 'Holding Company',
    formationType: 'LLC',
    functionalCurrency: 'USD',
    taxReportingStatus: 'None',
    annualRevenue: '$25,000,000',
    context: {
      fundFamilyLabel: 'Blackstone Real Estate Partners',
      fundLabel: 'BREP IX',
      parentContextLabel: 'Real estate holding entity',
    },
    activityLog: [
      { date: '2026-03-20', action: 'Year-end allocations reviewed', actor: 'Maria Lopez' },
    ],
    comments: [],
  },
  // --- Blocker ---
  {
    id: 'brep-ix-blocker-lux',
    name: 'BREP IX Blocker Lux S.a r.l.',
    legalName: 'BREP IX Blocker Lux S.a r.l.',
    category: 'Blocker',
    jurisdiction: 'Luxembourg',
    status: 'Pending Review',
    taxClassification: 'Corporation',
    ownerTeam: 'International Tax',
    scopeIds: ['blackstone-re-ix', 'tax-year-2026'],
    associatedFundIds: ['blackstone-re-ix'],
    associatedDealIds: [],
    structureSummary: 'Luxembourg blocker entity for tax-exempt and non-US investors in BREP IX.',
    requestCount: 4,
    documentCount: 11,
    openQuestions: 3,
    lastReviewDate: '2026-03-16',
    notes: 'Lux blocker with ECI, withholding, and ownership tracing requirements.',
    ein: '98-1112233',
    dateFormed: '2019-09-01',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'Luxembourg Corp Services S.A.',
    address: '2 Rue du Fort Bourbon, L-1249 Luxembourg',
    checkTheBoxElection: 'Elected corporation — Form 8832 filed 2019',
    treatyCountry: 'Luxembourg',
    fatcaStatus: 'Registered deemed-compliant FFI',
    stateFilingJurisdictions: [],
    structureRole: 'Blocker',
    formationType: 'Corp',
    functionalCurrency: 'EUR',
    taxReportingStatus: 'CFC',
    annualRevenue: '$12,500,000',
    context: {
      fundFamilyLabel: 'Blackstone Real Estate Partners',
      fundLabel: 'BREP IX',
      parentContextLabel: 'Lux blocker entity',
    },
    activityLog: [
      { date: '2026-03-16', action: 'Withholding rate review flagged for update', actor: 'David Kim' },
      { date: '2026-03-05', action: 'Treaty position documented', actor: 'Maria Lopez' },
    ],
    comments: [],
  },
  // --- BIP Master Fund Vehicle ---
  {
    id: 'atlas-master-fund',
    name: 'BIP Master Fund',
    legalName: 'BIP Master Fund, L.P.',
    category: 'Fund Vehicle',
    jurisdiction: 'Cayman Islands',
    status: 'Active',
    taxClassification: 'Partnership',
    ownerTeam: 'Fund Tax',
    scopeIds: ['bip-i', 'tax-year-2026'],
    associatedFundIds: ['bip-i'],
    associatedDealIds: ['atlas-infra-acquisition', 'atlas-lux-debt-facility', 'smith-re-equity-roll'],
    structureSummary: 'Primary master fund — top-level owner across BIP structures.',
    requestCount: 4,
    documentCount: 12,
    openQuestions: 1,
    lastReviewDate: '2026-03-18',
    notes: 'Master fund entity for BIP-related investments and ownership structures.',
    ein: '98-7654321',
    dateFormed: '2018-06-15',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'Maples Corporate Services',
    address: 'PO Box 309, Ugland House, George Town, Grand Cayman',
    checkTheBoxElection: 'N/A — foreign partnership',
    treatyCountry: 'Cayman Islands',
    fatcaStatus: 'Sponsoring entity — IGA Model 1',
    stateFilingJurisdictions: [],
    structureRole: 'Master Fund',
    formationType: 'LP',
    functionalCurrency: 'USD',
    taxReportingStatus: 'None',
    annualRevenue: '$62,000,000',
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP Master Fund',
      parentContextLabel: 'Fund vehicle',
    },
    activityLog: [],
    comments: [],
  },
  // --- Atlas Operating Companies ---
  {
    id: 'smith-real-estate-llc',
    name: 'Smith Real Estate LLC',
    legalName: 'Smith Real Estate LLC',
    category: 'Investment Level',
    jurisdiction: 'Delaware',
    status: 'Active',
    taxClassification: 'Partnership',
    ownerTeam: 'Portfolio Reporting',
    scopeIds: ['bip-i', 'fed-state-compliance', 'tax-year-2026'],
    associatedFundIds: [],
    associatedDealIds: ['atlas-infra-acquisition', 'smith-re-equity-roll'],
    structureSummary: 'Operating company owned by BIP Master Fund — real estate portfolio.',
    requestCount: 2,
    documentCount: 5,
    openQuestions: 0,
    lastReviewDate: '2026-03-15',
    notes: 'OpCo for Smith RE portfolio — subsidiary of BIP Master Fund.',
    ein: '47-5559876',
    dateFormed: '2020-03-01',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'Corporation Trust Company',
    address: '1209 Orange St, Wilmington, DE 19801',
    checkTheBoxElection: 'N/A — domestic partnership',
    treatyCountry: 'N/A',
    fatcaStatus: 'N/A — domestic entity',
    stateFilingJurisdictions: ['Delaware', 'New York'],
    structureRole: 'Operating Company',
    formationType: 'LLC',
    functionalCurrency: 'USD',
    taxReportingStatus: 'None',
    annualRevenue: '$8,500,000',
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP Master Fund',
      parentContextLabel: 'Smith RE OpCo',
    },
    activityLog: [],
    comments: [],
  },
  {
    id: 'drip-ventures-inc',
    name: 'Drip Ventures Inc',
    legalName: 'Drip Ventures Inc.',
    category: 'Investment Level',
    jurisdiction: 'Delaware',
    status: 'Active',
    taxClassification: 'Corporation',
    ownerTeam: 'Portfolio Reporting',
    scopeIds: ['bip-i', 'fed-state-compliance', 'tax-year-2026'],
    associatedFundIds: [],
    associatedDealIds: ['smith-re-equity-roll'],
    structureSummary: 'Operating company — subsidiary of Smith Real Estate LLC.',
    requestCount: 1,
    documentCount: 3,
    openQuestions: 0,
    lastReviewDate: '2026-03-12',
    notes: 'OpCo subsidiary of Smith RE LLC within Atlas structure.',
    ein: '82-4437891',
    dateFormed: '2021-01-10',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'CSC — Lawyers Incorporating Service',
    address: '251 Little Falls Dr, Wilmington, DE 19808',
    checkTheBoxElection: 'N/A — domestic corporation',
    treatyCountry: 'N/A',
    fatcaStatus: 'N/A — domestic entity',
    stateFilingJurisdictions: ['Delaware', 'California'],
    structureRole: 'Operating Company',
    formationType: 'Corp',
    functionalCurrency: 'USD',
    taxReportingStatus: 'None',
    annualRevenue: '$3,200,000',
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP Master Fund',
      parentContextLabel: 'Drip Ventures OpCo',
    },
    activityLog: [],
    comments: [],
  },
  // --- ASPI Blocker ---
  {
    id: 'atlas-blocker-lux',
    name: 'ASPI Blocker',
    legalName: 'ASPI Blocker S.a r.l.',
    category: 'Blocker',
    jurisdiction: 'Luxembourg',
    status: 'Active',
    taxClassification: 'Corporation',
    ownerTeam: 'International Tax',
    scopeIds: ['bx-infra-i', 'bip-i', 'tax-year-2026'],
    associatedFundIds: ['bx-infra-i', 'bip-i'],
    associatedDealIds: ['atlas-lux-debt-facility', 'smith-re-equity-roll'],
    structureSummary: 'Luxembourg blocker entity owned by BIP Master Fund for non-US investor access.',
    requestCount: 3,
    documentCount: 8,
    openQuestions: 1,
    lastReviewDate: '2026-03-16',
    notes: 'Lux blocker with ECI, withholding, and ownership tracing requirements.',
    ein: '98-1112233',
    dateFormed: '2019-09-01',
    fiscalYearEnd: 'December 31',
    registeredAgent: 'Luxembourg Corp Services S.A.',
    address: '2 Rue du Fort Bourbon, L-1249 Luxembourg',
    checkTheBoxElection: 'Elected corporation — Form 8832 filed 2019',
    treatyCountry: 'Luxembourg',
    fatcaStatus: 'Registered deemed-compliant FFI',
    stateFilingJurisdictions: [],
    structureRole: 'Blocker',
    formationType: 'Corp',
    functionalCurrency: 'EUR',
    taxReportingStatus: 'CFC',
    annualRevenue: '$15,000,000',
    context: {
      fundFamilyLabel: 'Brookfield Infrastructure Partners',
      fundLabel: 'BIP Master Fund',
      parentContextLabel: 'Lux blocker entity',
    },
    activityLog: [],
    comments: [],
  },
  // --- Third-Party ---
  {
    id: 'third-party-investors',
    name: 'Third-Party Investors',
    legalName: 'Third-Party Investors',
    category: 'Third-Party',
    jurisdiction: 'N/A',
    status: 'Active',
    taxClassification: '',
    ownerTeam: '',
    scopeIds: ['tax-year-2026'],
    associatedFundIds: [],
    associatedDealIds: [],
    structureSummary: 'Represents external third-party ownership stakes across the structure.',
    requestCount: 0,
    documentCount: 0,
    openQuestions: 0,
    lastReviewDate: '',
    notes: 'Placeholder entity representing aggregate third-party / external ownership interests.',
    ein: '',
    dateFormed: '',
    fiscalYearEnd: '',
    registeredAgent: '',
    address: '',
    checkTheBoxElection: '',
    treatyCountry: '',
    fatcaStatus: '',
    stateFilingJurisdictions: [],
    structureRole: 'Third-Party',
    formationType: '',
    functionalCurrency: 'USD',
    taxReportingStatus: '',
    annualRevenue: '',
    context: {
      fundFamilyLabel: '',
      fundLabel: '',
      parentContextLabel: 'External ownership interests',
    },
    activityLog: [],
    comments: [],
  },
];

export const entitiesService = {
  getAccessibleEntities(): EntityRecord[] {
    return ENTITY_RECORDS;
  },

  getScopedEntities(selection: ScopeSelection): EntityRecord[] {
    return ENTITY_RECORDS.filter((entity) => {
      const effectiveScopeIds = [...entity.scopeIds, ...entity.associatedDealIds];
      if (!matchesScope(effectiveScopeIds, selection)) return false;
      if (
        selection.entityCategoryIds.length > 0 &&
        !selection.entityCategoryIds.includes(entity.category)
      ) {
        return false;
      }
      return true;
    });
  },

  getAccessibleEntityById(id: string): EntityRecord | undefined {
    return ENTITY_RECORDS.find((entity) => entity.id === id);
  },

  getVersion(): number {
    return _version;
  },

  subscribe(cb: Listener): () => void {
    _listeners.add(cb);
    return () => _listeners.delete(cb);
  },

  addEntity(entity: EntityRecord): void {
    ENTITY_RECORDS = [entity, ...ENTITY_RECORDS];
    _version++;
    _notify();
  },

  updateEntity(id: string, updates: Partial<Omit<EntityRecord, 'id'>>): void {
    ENTITY_RECORDS = ENTITY_RECORDS.map((e) => (e.id === id ? { ...e, ...updates } : e));
    _version++;
    _notify();
  },

  deleteEntity(id: string): void {
    ENTITY_RECORDS = ENTITY_RECORDS.filter((e) => e.id !== id);
    _version++;
    _notify();
  },

  addEntityComment(id: string, comment: RecordComment): void {
    ENTITY_RECORDS = ENTITY_RECORDS.map((e) =>
      e.id === id ? { ...e, comments: [...e.comments, comment] } : e
    );
    _version++;
    _notify();
  },
};
